/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Paquetes.Mensaje;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JTextArea;

/**
 *
 * @author Camila
 */
public class ChatGUI extends javax.swing.JFrame {
    private Color colorMensajePropio = new Color(241, 179, 154);
    private Color colorMensajeInterlocutor = new Color(179, 214, 23);
    private int codigoDestinatario;

    /**
     * Creates new form ChatGUI
     */
    public ChatGUI(String nombreEmpleado,ArrayList<Mensaje> mensajes,
            int codigoDestinatario) {
        this.codigoDestinatario = codigoDestinatario;
        initComponents();
        setVisible(true);
        setTitle(nombreEmpleado);        
        cargarMensages(mensajes);
    }
    
    public void cargarMensages(ArrayList<Mensaje> mensajes) {
        panelMessages.removeAll();
        GridBagConstraints restriccion = new GridBagConstraints();
        for(Mensaje mensaje : mensajes){
            JTextArea mensajeGUI = new JTextArea(mensaje.getContenido());
            mensajeGUI.setEditable(false);
            mensajeGUI.setToolTipText(mensaje.getFecha().concat("\n ").
                    concat(mensaje.getHora()));
            mensajeGUI.setLineWrap(true);
            if(mensaje.getPropio()){
                mensajeGUI.setBackground(colorMensajePropio);
            } else {
                mensajeGUI.setBackground(colorMensajeInterlocutor);
            }
            restriccion.gridx = 0;
            restriccion.gridy = panelMessages.getComponentCount();
            restriccion.fill = GridBagConstraints.HORIZONTAL;
            restriccion.insets = new Insets(2, 4, 2, 4);
            restriccion.weightx = 1.0;
            restriccion.ipady = 6*mensajeGUI.getLineCount();
            panelMessages.add(mensajeGUI,restriccion);
        };  
        panelMessages.revalidate();
        panelMessages.invalidate();
        repaint();
    }
    
    public String obtenerMensaje(){
        return txtMensage.getText().trim();
    }

    public void limpiarTxtMensaje(){
        txtMensage.setColumns(0);
        txtMensage.setRows(0);
        txtMensage.setText(null);
        txtMensage.validate();
        txtMensage.repaint();   
        scrollMensage.getVerticalScrollBar().setValue(0);
        scrollMensage.repaint();
    }

    public int getCodigoDestinatario() {
        return codigoDestinatario;
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();
        btnEnviar = new javax.swing.JButton();
        scrollMensage = new javax.swing.JScrollPane();
        txtMensage = new javax.swing.JTextArea();
        scrollMensages = new javax.swing.JScrollPane();
        panelMessages = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(85, 85, 85));
        setResizable(false);

        PanelContenedor.setBackground(new java.awt.Color(186, 232, 217));
        PanelContenedor.setForeground(new java.awt.Color(235, 0, 235));
        PanelContenedor.setToolTipText("");

        btnEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/enviarMensaje_icon.png"))); // NOI18N
        btnEnviar.setToolTipText("Enviar mensaje");

        txtMensage.setColumns(20);
        txtMensage.setLineWrap(true);
        scrollMensage.setViewportView(txtMensage);

        panelMessages.setBackground(new java.awt.Color(242, 242, 240));
        panelMessages.setLayout(new java.awt.GridBagLayout());
        scrollMensages.setViewportView(panelMessages);

        javax.swing.GroupLayout PanelContenedorLayout = new javax.swing.GroupLayout(PanelContenedor);
        PanelContenedor.setLayout(PanelContenedorLayout);
        PanelContenedorLayout.setHorizontalGroup(
            PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContenedorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollMensages)
                    .addGroup(PanelContenedorLayout.createSequentialGroup()
                        .addComponent(scrollMensage, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        PanelContenedorLayout.setVerticalGroup(
            PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollMensages, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEnviar)
                    .addComponent(scrollMensage, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void setKeyListener(KeyListener kl){
        txtMensage.addKeyListener(kl);
    }
    
    public void setActionListener(ActionListener al){
        btnEnviar.addActionListener(al);
    }
    
    public void setWindowsListener(WindowListener wl){
        addWindowListener(wl);
    }
    
    public void saltoLineaMensaje(){
        txtMensage.setText(obtenerMensaje().concat("\n"));
    }

    public JButton getBtnEnviar() {
        return btnEnviar;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JPanel panelMessages;
    private javax.swing.JScrollPane scrollMensage;
    private javax.swing.JScrollPane scrollMensages;
    private javax.swing.JTextArea txtMensage;
    // End of variables declaration//GEN-END:variables
}
