/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Paquetes.Publicaciones;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import vista.PrincipalGUI;

/**
 *
 * @author danie
 */
public class PerfilUsuarios extends javax.swing.JFrame {
    private String descripcionEmpleado;
    private String sexo;
    private ArrayList<JCheckBox> checkBoxesPublicaciones;
    /**
     * Creates new form PerfilUsuarios
     */
    public PerfilUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Info_Perfil = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblNombreValor = new javax.swing.JLabel();
        lblCorreoValor = new javax.swing.JLabel();
        lblDependenciaValor = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblDependencia = new javax.swing.JLabel();
        lblSubdependencia = new javax.swing.JLabel();
        lblSubdependenciaValor = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDescripcion = new javax.swing.JTextArea();
        pane_lbl_Informacion = new javax.swing.JPanel();
        lblInfomacionIcon = new javax.swing.JLabel();
        lblInformacion = new javax.swing.JLabel();
        panelPublicaciones = new javax.swing.JPanel();
        pane_lbl_Publicaciones = new javax.swing.JPanel();
        lblInfomacionIcon1 = new javax.swing.JLabel();
        lblInformacion1 = new javax.swing.JLabel();
        scrollPanePublicaciones = new javax.swing.JScrollPane();
        panelContenedorPublicaciones = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_Info_Perfil.setBackground(new java.awt.Color(217, 217, 232));
        panel_Info_Perfil.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(107, 129, 179), 3, true));
        panel_Info_Perfil.setPreferredSize(new java.awt.Dimension(900, 374));

        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perfil_hombre_icon.png"))); // NOI18N

        lblNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombre.setText("Nombre: ");

        lblNombreValor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNombreValor.setText("Dylan Caicedo");

        lblCorreoValor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCorreoValor.setText("dilan.joel2002@hotmail.com");

        lblDependenciaValor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDependenciaValor.setText("Facultades");

        lblCorreo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCorreo.setText("Correo electrónico:");

        lblDependencia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDependencia.setText("Dependecia:");

        lblSubdependencia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSubdependencia.setText("Subdependecia:");

        lblSubdependenciaValor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSubdependenciaValor.setText("Ingenieria");

        lblDescripcion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDescripcion.setText("Descripción");

        txtAreaDescripcion.setEditable(false);
        txtAreaDescripcion.setBackground(new java.awt.Color(242, 242, 247));
        txtAreaDescripcion.setColumns(20);
        txtAreaDescripcion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtAreaDescripcion.setLineWrap(true);
        txtAreaDescripcion.setToolTipText("");
        jScrollPane1.setViewportView(txtAreaDescripcion);

        pane_lbl_Informacion.setBackground(new java.awt.Color(242, 242, 247));

        lblInfomacionIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informacion_icon.png"))); // NOI18N
        pane_lbl_Informacion.add(lblInfomacionIcon);

        lblInformacion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblInformacion.setText("Información del Empleado");
        lblInformacion.setToolTipText("");
        pane_lbl_Informacion.add(lblInformacion);

        javax.swing.GroupLayout panel_Info_PerfilLayout = new javax.swing.GroupLayout(panel_Info_Perfil);
        panel_Info_Perfil.setLayout(panel_Info_PerfilLayout);
        panel_Info_PerfilLayout.setHorizontalGroup(
            panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Info_PerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_Info_PerfilLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pane_lbl_Informacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Info_PerfilLayout.createSequentialGroup()
                        .addGroup(panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_Info_PerfilLayout.createSequentialGroup()
                                .addGroup(panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre)
                                    .addComponent(lblCorreo)
                                    .addComponent(lblSubdependencia)
                                    .addComponent(lblDependencia))
                                .addGap(49, 49, 49)
                                .addGroup(panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panel_Info_PerfilLayout.createSequentialGroup()
                                        .addGroup(panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCorreoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblDependenciaValor)
                                            .addComponent(lblSubdependenciaValor))
                                        .addGap(0, 189, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(panel_Info_PerfilLayout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(lblDescripcion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9))
        );
        panel_Info_PerfilLayout.setVerticalGroup(
            panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Info_PerfilLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(pane_lbl_Informacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_Info_PerfilLayout.createSequentialGroup()
                        .addGroup(panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(lblNombreValor))
                        .addGap(9, 9, 9)
                        .addGroup(panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorreo)
                            .addComponent(lblCorreoValor))
                        .addGap(9, 9, 9)
                        .addGroup(panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDependencia)
                            .addComponent(lblDependenciaValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSubdependencia)
                            .addComponent(lblSubdependenciaValor))
                        .addGap(36, 36, 36)
                        .addComponent(lblDescripcion))
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        panelPublicaciones.setBackground(new java.awt.Color(217, 217, 232));
        panelPublicaciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(107, 129, 179), 3, true));

        pane_lbl_Publicaciones.setBackground(new java.awt.Color(242, 242, 247));

        lblInfomacionIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/publicacion_icon.png"))); // NOI18N
        pane_lbl_Publicaciones.add(lblInfomacionIcon1);

        lblInformacion1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblInformacion1.setText("Mis publicaciones");
        lblInformacion1.setToolTipText("");
        pane_lbl_Publicaciones.add(lblInformacion1);

        panelContenedorPublicaciones.setBackground(new java.awt.Color(235, 30, 0));
        panelContenedorPublicaciones.setLayout(new java.awt.GridBagLayout());
        scrollPanePublicaciones.setViewportView(panelContenedorPublicaciones);

        javax.swing.GroupLayout panelPublicacionesLayout = new javax.swing.GroupLayout(panelPublicaciones);
        panelPublicaciones.setLayout(panelPublicacionesLayout);
        panelPublicacionesLayout.setHorizontalGroup(
            panelPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPublicacionesLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panelPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pane_lbl_Publicaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPanePublicaciones))
                .addGap(9, 9, 9))
        );
        panelPublicacionesLayout.setVerticalGroup(
            panelPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPublicacionesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pane_lbl_Publicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(scrollPanePublicaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 637, Short.MAX_VALUE)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelPublicaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel_Info_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 326, Short.MAX_VALUE)
                .addComponent(panelPublicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel_Info_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(252, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    
    
   
    
    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilUsuarios().setVisible(true);
            }
        });
    }

    */
    
    public void cargarInformacion(String nombre, String correo,
            String dependencia, String subdepenencia, String descripcion,
            String sexo,byte[]foto) {

        try {
            descripcionEmpleado = descripcion;
            lblNombreValor.setText(nombre);
            lblCorreoValor.setText(correo);
            lblDependenciaValor.setText(dependencia);
            lblSubdependenciaValor.setText(subdepenencia);
            txtAreaDescripcion.setText(descripcion);
            
            //Daniel
            BufferedImage image = null;
            InputStream in = new ByteArrayInputStream(foto);
            image = ImageIO.read(in);
            ImageIcon imgi = new ImageIcon(image.getScaledInstance(150, 150, 0));
            lblFoto.setIcon(imgi);
            //Daniel            
            
        } catch (IOException ex) {
            Logger.getLogger(PrincipalGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //cargarImagenPerfil(sexo);
        
    }
    /*
    public void cargarImagenPerfil(String sexo) {
        this.sexo = sexo;
        ImageIcon fotoPerfil;

        if (sexo.equals("Masculino")) {
            fotoPerfil = new ImageIcon(getClass().getResource("/imagenes"
                    + "/perfil_hombre_icon.png"));
            lblFoto.setIcon(fotoPerfil);

        } else {

            fotoPerfil = new ImageIcon(getClass().getResource("/imagenes"
                    + "/perfil_mujer_icon.jpg"));
            lblFoto.setIcon(fotoPerfil);

        }

    }
    */
    public void cargarPublicaciones(Publicaciones publicaciones) {
        
        List<Paquetes.Publicacion> listaPublicaciones;
        listaPublicaciones = publicaciones.obtenerPublicaciones();

        for (Paquetes.Publicacion publicacionPaquete : listaPublicaciones) {

            Publicacion publicacion = new Publicacion(publicacionPaquete.getId_Publicacion(),
                    publicacionPaquete.getFecha(), publicacionPaquete.getHora(),
                    publicacionPaquete.getContenido());

            GridBagConstraints restriccion = new GridBagConstraints();
            restriccion.gridx = 0;
            restriccion.gridy = panelContenedorPublicaciones.getComponentCount();
            restriccion.fill = GridBagConstraints.HORIZONTAL;
            restriccion.insets = new Insets(2, 0, 2, 0);
            restriccion.weightx = 1.0;
            restriccion.ipady = 100;
           // checkBoxesPublicaciones.add(publicacion.getCheckBoxBorrar());
            panelContenedorPublicaciones.add(publicacion, restriccion);
        }

        panelContenedorPublicaciones.revalidate();
        panelContenedorPublicaciones.invalidate();
        repaint();

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreoValor;
    private javax.swing.JLabel lblDependencia;
    private javax.swing.JLabel lblDependenciaValor;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblInfomacionIcon;
    private javax.swing.JLabel lblInfomacionIcon1;
    private javax.swing.JLabel lblInformacion;
    private javax.swing.JLabel lblInformacion1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreValor;
    private javax.swing.JLabel lblSubdependencia;
    private javax.swing.JLabel lblSubdependenciaValor;
    private javax.swing.JPanel pane_lbl_Informacion;
    private javax.swing.JPanel pane_lbl_Publicaciones;
    private javax.swing.JPanel panelContenedorPublicaciones;
    private javax.swing.JPanel panelPublicaciones;
    private javax.swing.JPanel panel_Info_Perfil;
    private javax.swing.JScrollPane scrollPanePublicaciones;
    private javax.swing.JTextArea txtAreaDescripcion;
    // End of variables declaration//GEN-END:variables
}
