/**
 * El propósito de la clase es servir de vista (JForm) para la ventana principal
 */
package vista;

import Paquetes.Publicaciones;
import Vista.Empleado;
import Vista.Publicacion;
import Vista.TMEmpleado;
import Vista.itemCombo;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;


public class PrincipalGUI extends javax.swing.JFrame {
    
    private ArrayList<Vista.itemCombo> dependencias;
    private ArrayList<ArrayList<Vista.itemCombo>> subdependencias;
    private TMEmpleado tableModel;
    
    public PrincipalGUI() {
        //setExtendedState(MAXIMIZED_BOTH);
        tableModel = new TMEmpleado();
        initComponents();
        checkBoxesPublicaciones = new ArrayList();
        setVisible(true);
    }

    
    public void setDependencias(ArrayList<itemCombo> dependencias) {
        this.dependencias = dependencias;
    }

    public void setSubdependencias(ArrayList<ArrayList<itemCombo>> subdependencias) {
        this.subdependencias = subdependencias;
    }

    public void llenarCbxDependencias(){
        
        for(itemCombo item: dependencias){
            cbxDependecia.addItem(item);
        }
    }
    
    /**
     * El propósito del método es cargar toda la información del Empleado al
     * panel del Perfil (solo su información)
     *
     * @param nombre
     * @param correo
     * @param dependencia
     * @param subdepenencia
     * @param descripcion
     * @param sexo
     */
    public void cargarInformacion(String nombre, String correo,
            String dependencia, String subdepenencia, String descripcion, 
            String sexo,byte[] foto) {//DANIEL

        try {
            descripcionEmpleado = descripcion;

            lblNombreValor.setText(nombre);
            lblCorreoValor.setText(correo);
            lblDependenciaValor.setText(dependencia);
            lblSubdependenciaValor.setText(subdepenencia);
            txtAreaDescripcion.setText(descripcion);

        //Daniel
            BufferedImage image = null;
            InputStream in = new ByteArrayInputStream(foto);
            image = ImageIO.read(in);
            ImageIcon imgi = new ImageIcon(image.getScaledInstance(150, 150, 0));
            lblFoto.setIcon(imgi);
        //Daniel
            
            
        } catch (IOException ex) {
            System.out.println("Metodo cargarInformacion-PrincipalGUI " + ex);
        }
    }
    private void btnCambiarFotoActionPerformed(java.awt.event.ActionEvent evt) {                                               

    }
    /**
     * El propósito del método es cargar la imagen del perfil según el sexo del
     * Empleado
     *
     * @param sexo
     */
    public void cargarImagenPerfil(String sexo) {
        this.sexo = sexo;
        ImageIcon fotoPerfil;

        if (sexo.equals("Masculino")) {
            fotoPerfil = new ImageIcon(getClass().getResource("/imagenes"
                    + "/perfil_hombre_icon.png"));
            lblFoto.setIcon(fotoPerfil);

        } else {

            fotoPerfil = new ImageIcon(getClass().getResource("/imagenes"
                    + "/perfil_mujer_icon.jpg"));
            lblFoto.setIcon(fotoPerfil);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ventana = new javax.swing.JTabbedPane();
        panelPerfil = new javax.swing.JPanel(){

            @Override
            public void paint(Graphics g) {
                Dimension tamanio = getSize();
                ImageIcon imagen;

                imagen = new ImageIcon(getClass().getResource("/imagenes/fondo_ventana_principal.jpg"));
                g.drawImage(imagen.getImage(),0,0,tamanio.width,tamanio.height,null);
                setOpaque(false);
                super.paint(g);
            }
        };
        panel_Info_Perfil = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblNombreValor = new javax.swing.JLabel();
        lblCorreoValor = new javax.swing.JLabel();
        lblDependenciaValor = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblDependencia = new javax.swing.JLabel();
        lblSubdependencia = new javax.swing.JLabel();
        lblSubdependenciaValor = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDescripcion = new javax.swing.JTextArea();
        btnModificarDescripcion = new javax.swing.JButton();
        pane_lbl_Informacion = new javax.swing.JPanel();
        lblInfomacionIcon = new javax.swing.JLabel();
        lblInformacion = new javax.swing.JLabel();
        btnCambiarFoto = new javax.swing.JButton();
        panelPublicaciones = new javax.swing.JPanel();
        pane_lbl_Publicaciones = new javax.swing.JPanel();
        lblInfomacionIcon1 = new javax.swing.JLabel();
        lblInformacion1 = new javax.swing.JLabel();
        scrollPanePublicaciones = new javax.swing.JScrollPane();
        panelContenedorPublicaciones = new javax.swing.JPanel();
        panelControlPublicacion = new javax.swing.JPanel();
        btnEscribirPublicacion = new javax.swing.JButton();
        btnEliminarPublicacion = new javax.swing.JButton();
        btnControlPublicaciones = new javax.swing.JButton();
        panelBandeja = new javax.swing.JPanel(){
            @Override
            public void paint(Graphics g) {
                Dimension tamanio = getSize();
                ImageIcon imagen;

                imagen = new ImageIcon(getClass().getResource("/imagenes/fondo_ventana_principal.jpg"));
                g.drawImage(imagen.getImage(),0,0,tamanio.width,tamanio.height,null);
                setOpaque(false);
                super.paint(g);
            }
        };
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtNombreBandeja = new javax.swing.JTextField();
        btnBuscarMensaje = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        btnAbrirChat = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        panelBuscador = new javax.swing.JPanel(){
            @Override
            public void paint(Graphics g) {
                Dimension tamanio = getSize();
                ImageIcon imagen;

                imagen = new ImageIcon(getClass().getResource("/imagenes/fondo_ventana_principal.jpg"));
                g.drawImage(imagen.getImage(),0,0,tamanio.width,tamanio.height,null);
                setOpaque(false);
                super.paint(g);
            }
        };
        jLabel13 = new javax.swing.JLabel();
        panelBusqueda = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbxDependecia = new javax.swing.JComboBox<>();
        cbxSubdependecia = new javax.swing.JComboBox<>();
        txtNombreBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        scrollTable = new javax.swing.JScrollPane();
        tablaBusqueda = new javax.swing.JTable(){

            public String getToolTipText(MouseEvent e) {
                String tip = null;
                java.awt.Point p = e.getPoint();
                int rowIndex = rowAtPoint(p);
                int colIndex = columnAtPoint(p);

                try {
                    tip = getValueAt(rowIndex, colIndex).toString();
                } catch (RuntimeException e1) {
                    //catch null pointer exception if mouse is over an empty line
                }

                return tip;

            }
        };
        btnEnviarMensaje = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnVerPerfil = new javax.swing.JButton();
        panelNotificaciones = new javax.swing.JPanel(){
            @Override
            public void paint(Graphics g) {
                Dimension tamanio = getSize();
                ImageIcon imagen;

                imagen = new ImageIcon(getClass().getResource("/imagenes/fondo_ventana_principal.jpg"));
                g.drawImage(imagen.getImage(),0,0,tamanio.width,tamanio.height,null);
                setOpaque(false);
                super.paint(g);
            }
        };
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaNotificaciones = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NetU");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/netU_icon.png")));
        getContentPane().setLayout(new java.awt.CardLayout());

        Ventana.setToolTipText("");

        panel_Info_Perfil.setBackground(new java.awt.Color(217, 217, 232));
        panel_Info_Perfil.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(107, 129, 179), 3, true));
        panel_Info_Perfil.setPreferredSize(new java.awt.Dimension(900, 374));

        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perfil_hombre_icon.png"))); // NOI18N

        lblNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombre.setText("Nombre: ");

        lblNombreValor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNombreValor.setText("Dylan Caicedo");

        lblCorreoValor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCorreoValor.setText("dilan.joel2002@hotmail.com");

        lblDependenciaValor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDependenciaValor.setText("Facultades");

        lblCorreo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCorreo.setText("Correo electrónico:");

        lblDependencia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDependencia.setText("Dependecia:");

        lblSubdependencia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSubdependencia.setText("Subdependecia:");

        lblSubdependenciaValor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSubdependenciaValor.setText("Ingenieria");

        lblDescripcion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDescripcion.setText("Descripción");

        txtAreaDescripcion.setEditable(false);
        txtAreaDescripcion.setBackground(new java.awt.Color(242, 242, 247));
        txtAreaDescripcion.setColumns(20);
        txtAreaDescripcion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtAreaDescripcion.setLineWrap(true);
        txtAreaDescripcion.setToolTipText("");
        jScrollPane1.setViewportView(txtAreaDescripcion);

        btnModificarDescripcion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnModificarDescripcion.setForeground(new java.awt.Color(235, 30, 0));
        btnModificarDescripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cambiarDescripcion_icon.png"))); // NOI18N
        btnModificarDescripcion.setText("Editar descripción");
        btnModificarDescripcion.setToolTipText("");
        btnModificarDescripcion.setPreferredSize(new java.awt.Dimension(160, 44));

        pane_lbl_Informacion.setBackground(new java.awt.Color(242, 242, 247));

        lblInfomacionIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informacion_icon.png"))); // NOI18N
        pane_lbl_Informacion.add(lblInfomacionIcon);

        lblInformacion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblInformacion.setLabelFor(lblInfomacionIcon);
        lblInformacion.setText("Mi información");
        lblInformacion.setToolTipText("");
        pane_lbl_Informacion.add(lblInformacion);

        btnCambiarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconfinder-cameravideophotorecordingdevicevlog-3993861_112653.png"))); // NOI18N
        btnCambiarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_Info_PerfilLayout = new javax.swing.GroupLayout(panel_Info_Perfil);
        panel_Info_Perfil.setLayout(panel_Info_PerfilLayout);
        panel_Info_PerfilLayout.setHorizontalGroup(
            panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Info_PerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_Info_PerfilLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCambiarFoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificarDescripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pane_lbl_Informacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Info_PerfilLayout.createSequentialGroup()
                        .addGroup(panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_Info_PerfilLayout.createSequentialGroup()
                                .addGroup(panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre)
                                    .addComponent(lblCorreo)
                                    .addComponent(lblSubdependencia)
                                    .addComponent(lblDependencia))
                                .addGap(49, 49, 49)
                                .addGroup(panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panel_Info_PerfilLayout.createSequentialGroup()
                                        .addGroup(panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCorreoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblDependenciaValor)
                                            .addComponent(lblSubdependenciaValor))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(panel_Info_PerfilLayout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(lblDescripcion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9))
        );
        panel_Info_PerfilLayout.setVerticalGroup(
            panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Info_PerfilLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(pane_lbl_Informacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_Info_PerfilLayout.createSequentialGroup()
                        .addGroup(panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(lblNombreValor))
                        .addGap(9, 9, 9)
                        .addGroup(panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorreo)
                            .addComponent(lblCorreoValor))
                        .addGap(9, 9, 9)
                        .addGroup(panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDependencia)
                            .addComponent(lblDependenciaValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSubdependencia)
                            .addComponent(lblSubdependenciaValor))
                        .addGap(36, 36, 36)
                        .addComponent(lblDescripcion))
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_Info_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_Info_PerfilLayout.createSequentialGroup()
                        .addComponent(btnCambiarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificarDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9))
        );

        panelPublicaciones.setBackground(new java.awt.Color(217, 217, 232));
        panelPublicaciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(107, 129, 179), 3, true));

        pane_lbl_Publicaciones.setBackground(new java.awt.Color(242, 242, 247));

        lblInfomacionIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/publicacion_icon.png"))); // NOI18N
        pane_lbl_Publicaciones.add(lblInfomacionIcon1);

        lblInformacion1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblInformacion1.setLabelFor(lblInfomacionIcon);
        lblInformacion1.setText("Mis publicaciones");
        lblInformacion1.setToolTipText("");
        pane_lbl_Publicaciones.add(lblInformacion1);

        panelContenedorPublicaciones.setBackground(new java.awt.Color(235, 30, 0));
        panelContenedorPublicaciones.setLayout(new java.awt.GridBagLayout());
        scrollPanePublicaciones.setViewportView(panelContenedorPublicaciones);

        javax.swing.GroupLayout panelPublicacionesLayout = new javax.swing.GroupLayout(panelPublicaciones);
        panelPublicaciones.setLayout(panelPublicacionesLayout);
        panelPublicacionesLayout.setHorizontalGroup(
            panelPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPublicacionesLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panelPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pane_lbl_Publicaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPanePublicaciones))
                .addGap(9, 9, 9))
        );
        panelPublicacionesLayout.setVerticalGroup(
            panelPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPublicacionesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pane_lbl_Publicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(scrollPanePublicaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelControlPublicacion.setBackground(new java.awt.Color(217, 217, 232));
        panelControlPublicacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(107, 129, 179), 3, true));

        btnEscribirPublicacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEscribirPublicacion.setForeground(new java.awt.Color(235, 30, 0));
        btnEscribirPublicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/escribirPublicacion_icon.png"))); // NOI18N
        btnEscribirPublicacion.setText("Escribir publicación");
        btnEscribirPublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscribirPublicacionActionPerformed(evt);
            }
        });

        btnEliminarPublicacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEliminarPublicacion.setForeground(new java.awt.Color(235, 30, 0));
        btnEliminarPublicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminarPublicacion_icon.png"))); // NOI18N
        btnEliminarPublicacion.setText("Eliminar publicación");

        btnControlPublicaciones.setBackground(new java.awt.Color(242, 242, 247));
        btnControlPublicaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnControlPublicaciones.setForeground(new java.awt.Color(235, 30, 0));
        btnControlPublicaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/opcion_icon.png"))); // NOI18N
        btnControlPublicaciones.setText("Control de publicaciones");
        btnControlPublicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlPublicacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelControlPublicacionLayout = new javax.swing.GroupLayout(panelControlPublicacion);
        panelControlPublicacion.setLayout(panelControlPublicacionLayout);
        panelControlPublicacionLayout.setHorizontalGroup(
            panelControlPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlPublicacionLayout.createSequentialGroup()
                .addGroup(panelControlPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelControlPublicacionLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnControlPublicaciones))
                    .addGroup(panelControlPublicacionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelControlPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEscribirPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelControlPublicacionLayout.setVerticalGroup(
            panelControlPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlPublicacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnControlPublicaciones)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnEscribirPublicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarPublicacion)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPerfilLayout = new javax.swing.GroupLayout(panelPerfil);
        panelPerfil.setLayout(panelPerfilLayout);
        panelPerfilLayout.setHorizontalGroup(
            panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerfilLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addGroup(panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_Info_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPublicaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panelControlPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 838, Short.MAX_VALUE))
        );
        panelPerfilLayout.setVerticalGroup(
            panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerfilLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(panel_Info_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPerfilLayout.createSequentialGroup()
                        .addComponent(panelPublicaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addGroup(panelPerfilLayout.createSequentialGroup()
                        .addComponent(panelControlPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        Ventana.addTab("Mi perfil", new javax.swing.ImageIcon(getClass().getResource("/imagenes/perfil_Icon.png")), panelPerfil); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setText("Bandeja de Mensajes");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Nombre empleado:");

        btnBuscarMensaje.setText("Buscar");

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        btnAbrirChat.setText("Abrir Chat");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Antes de darle click al boton, seleccionar un empleado");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("NOTA:");

        javax.swing.GroupLayout panelBandejaLayout = new javax.swing.GroupLayout(panelBandeja);
        panelBandeja.setLayout(panelBandejaLayout);
        panelBandejaLayout.setHorizontalGroup(
            panelBandejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBandejaLayout.createSequentialGroup()
                .addGroup(panelBandejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBandejaLayout.createSequentialGroup()
                        .addGap(577, 577, 577)
                        .addComponent(jLabel21))
                    .addGroup(panelBandejaLayout.createSequentialGroup()
                        .addGap(474, 474, 474)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreBandeja, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBandejaLayout.createSequentialGroup()
                        .addGap(676, 676, 676)
                        .addComponent(btnAbrirChat))
                    .addGroup(panelBandejaLayout.createSequentialGroup()
                        .addGap(549, 549, 549)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23))
                    .addGroup(panelBandejaLayout.createSequentialGroup()
                        .addGap(524, 524, 524)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1172, Short.MAX_VALUE))
        );
        panelBandejaLayout.setVerticalGroup(
            panelBandejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBandejaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel21)
                .addGap(72, 72, 72)
                .addGroup(panelBandejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtNombreBandeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAbrirChat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBandejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addContainerGap(437, Short.MAX_VALUE))
        );

        Ventana.addTab("Mensajes", new javax.swing.ImageIcon(getClass().getResource("/imagenes/bandeja_icon.png")), panelBandeja); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Búsqueda de Empleados");

        panelBusqueda.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Dependencia:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Subdependencia:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Nombre Empleado:");

        cbxDependecia.setModel(new javax.swing.DefaultComboBoxModel<>(new itemCombo[] {new itemCombo(0, "TODAS") }));
        cbxDependecia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDependeciaActionPerformed(evt);
            }
        });

        cbxSubdependecia.setModel(new javax.swing.DefaultComboBoxModel<>(new itemCombo[] {new itemCombo(0, "TODAS") }));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel17.setText("Puedes iniciar la búsqueda sin un nombre");

        javax.swing.GroupLayout panelBusquedaLayout = new javax.swing.GroupLayout(panelBusqueda);
        panelBusqueda.setLayout(panelBusquedaLayout);
        panelBusquedaLayout.setHorizontalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel14)
                .addGap(171, 171, 171)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(127, 127, 127))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBusquedaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(cbxDependecia, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(cbxSubdependecia, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(txtNombreBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBusquedaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        panelBusquedaLayout.setVerticalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxDependecia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxSubdependecia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Resultado de la Búsqueda");

        tablaBusqueda.setModel(tableModel);
        tablaBusqueda.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollTable.setViewportView(tablaBusqueda);

        btnEnviarMensaje.setText("Enviar mensaje");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Antes de dar click en cualquier boton, seleccionar un Empleado de la tabla");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("NOTA:");

        btnVerPerfil.setText("Ver Perfil");
        btnVerPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBuscadorLayout = new javax.swing.GroupLayout(panelBuscador);
        panelBuscador.setLayout(panelBuscadorLayout);
        panelBuscadorLayout.setHorizontalGroup(
            panelBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscadorLayout.createSequentialGroup()
                .addGroup(panelBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscadorLayout.createSequentialGroup()
                        .addGap(560, 560, 560)
                        .addComponent(jLabel13))
                    .addGroup(panelBuscadorLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addGroup(panelBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18)
                            .addComponent(panelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrollTable)))
                    .addGroup(panelBuscadorLayout.createSequentialGroup()
                        .addGap(487, 487, 487)
                        .addGroup(panelBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBuscadorLayout.createSequentialGroup()
                                .addComponent(btnVerPerfil)
                                .addGap(281, 281, 281)
                                .addComponent(btnEnviarMensaje))
                            .addGroup(panelBuscadorLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)))))
                .addContainerGap(968, Short.MAX_VALUE))
        );
        panelBuscadorLayout.setVerticalGroup(
            panelBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscadorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(panelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(panelBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviarMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerPerfil))
                .addGap(18, 18, 18)
                .addGroup(panelBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addContainerGap(363, Short.MAX_VALUE))
        );

        Ventana.addTab("Buscar empleados", new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar_icon.png")), panelBuscador); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Notificaciones");

        txtAreaNotificaciones.setEditable(false);
        txtAreaNotificaciones.setColumns(20);
        txtAreaNotificaciones.setRows(5);
        jScrollPane2.setViewportView(txtAreaNotificaciones);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Para ver los mensajes enviados ve a la pestaña de \"Bandeja de Mensajes\"");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("NOTA:");

        javax.swing.GroupLayout panelNotificacionesLayout = new javax.swing.GroupLayout(panelNotificaciones);
        panelNotificaciones.setLayout(panelNotificacionesLayout);
        panelNotificacionesLayout.setHorizontalGroup(
            panelNotificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNotificacionesLayout.createSequentialGroup()
                .addGroup(panelNotificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNotificacionesLayout.createSequentialGroup()
                        .addGap(630, 630, 630)
                        .addComponent(jLabel10))
                    .addGroup(panelNotificacionesLayout.createSequentialGroup()
                        .addGap(458, 458, 458)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelNotificacionesLayout.createSequentialGroup()
                        .addGap(492, 492, 492)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addContainerGap(1166, Short.MAX_VALUE))
        );
        panelNotificacionesLayout.setVerticalGroup(
            panelNotificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNotificacionesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel10)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelNotificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addContainerGap(517, Short.MAX_VALUE))
        );

        Ventana.addTab("Notificaciones", new javax.swing.ImageIcon(getClass().getResource("/imagenes/notificaciones_icon.png")), panelNotificaciones); // NOI18N

        getContentPane().add(Ventana, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnControlPublicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlPublicacionesActionPerformed

        Dimension dimensionPanelControl = panelControlPublicacion.getSize();
        Dimension nuevaDimension;
        if (dimensionPanelControl.height > 61) {
            nuevaDimension = new Dimension(dimensionPanelControl.width, 61);
        } else {
            nuevaDimension = new Dimension(dimensionPanelControl.width, 186);
        }

        panelControlPublicacion.setPreferredSize(nuevaDimension);
        panelControlPublicacion.setMaximumSize(nuevaDimension);
        panelControlPublicacion.setSize(nuevaDimension);
        panelPerfil.updateUI();
    }//GEN-LAST:event_btnControlPublicacionesActionPerformed
    /**
     * El propòsito del metodo es llamar al metodo escribirPublicacion
     *
     * @param evt
     */
    private void btnEscribirPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscribirPublicacionActionPerformed
        escribirPublicacion(btnModificarDescripcion.getActionListeners()[0]);
    }//GEN-LAST:event_btnEscribirPublicacionActionPerformed

    private void cbxDependeciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDependeciaActionPerformed
        cbxSubdependecia.removeAllItems();
        itemCombo item = (itemCombo) cbxDependecia.getSelectedItem();
        int posicionFila = dependencias.indexOf(item);
        ArrayList<itemCombo> fila;
        cbxSubdependecia.addItem(new itemCombo(0,"TODAS"));
        
        if(item.getId() == 0){
            return;
        }
        
        fila = subdependencias.get(posicionFila);
        
        for(itemCombo index: fila){
            cbxSubdependecia.addItem(index);
        }
        
    }//GEN-LAST:event_cbxDependeciaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVerPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerPerfilActionPerformed

     /**
     * El propósito del método es limpiar y eliminar los checkBoxes en el array
     * y las publicacions en el Panel Contenedor. Se utiliza cada vez que se usa
     * cargarPublicaciones()
     */
    public void eliminarPublicaciones() {
        checkBoxesPublicaciones.clear();
        panelContenedorPublicaciones.removeAll();
    }

    /**
     * El propósito del método es obtener el id de las publicaciones
     * seleccionadas para eliminarse.
     *
     * @return Una lista de enteros si existen publicaciones, null de lo
     * contrario
     */
    public List<Integer> obtenerPublicacionesSeleccionadas() {

        if (panelContenedorPublicaciones.getComponentCount() > 0) {
            List<Integer> idPublicaciones = new ArrayList();

            for (JCheckBox checkbox : checkBoxesPublicaciones) {

                if (checkbox.isSelected()) {
                    idPublicaciones.add(Integer.parseInt(checkbox.getName()));
                }

            }

            return idPublicaciones;
        } else {
            return null;
        }

    }

    public void desSeleccionarPublicaciones() {

        for (JCheckBox checkbox : checkBoxesPublicaciones) {

            if (checkbox.isSelected()) {
                checkbox.setSelected(false);
            }

        }

    }

    /**
     * El proposito del metodo es instanciar el Form EscribirPublicacion como un
     * Thread implementando Runneable
     *
     * @param escucha El controlador es quien escucharà
     */
    public void escribirPublicacion(ActionListener escucha) {

        Thread hiloEscrirPublicacion;
        escribirPublicacion = new EscribirPublicacion(this, escucha);
        hiloEscrirPublicacion = new Thread(escribirPublicacion);

        hiloEscrirPublicacion.start();

    }

    /**
     * El propósito del método es cargar y mostrar en el Form las publicaciones
     * del Empleado. Se utiliza cuando el empleado incia sesión, eliminar o crea
     * Publicaciones.
     *
     * @param publicaciones El array de PublicacionesPaquete del Empleado
     */
    public void cargarPublicaciones(Publicaciones publicaciones) {
        eliminarPublicaciones();
        List<Paquetes.Publicacion> listaPublicaciones;
        listaPublicaciones = publicaciones.obtenerPublicaciones();

        for (Paquetes.Publicacion publicacionPaquete : listaPublicaciones) {

            Publicacion publicacion = new Publicacion(publicacionPaquete.getId_Publicacion(),
                    publicacionPaquete.getFecha(), publicacionPaquete.getHora(),
                    publicacionPaquete.getContenido());

            GridBagConstraints restriccion = new GridBagConstraints();
            restriccion.gridx = 0;
            restriccion.gridy = panelContenedorPublicaciones.getComponentCount();
            restriccion.fill = GridBagConstraints.HORIZONTAL;
            restriccion.insets = new Insets(2, 0, 2, 0);
            restriccion.weightx = 1.0;
            restriccion.ipady = 100;
            checkBoxesPublicaciones.add(publicacion.getCheckBoxBorrar());
            panelContenedorPublicaciones.add(publicacion, restriccion);
        }

        panelContenedorPublicaciones.revalidate();
        panelContenedorPublicaciones.invalidate();
        repaint();

    }


    /**
     * El propósito del método es actualizar el Form para modificar la
     * descripcion
     *
     * @param tipo Si es 1, entonces inicia la modificacion de la descripcion.
     * Si es 2, entonces cancela/guarda la modificacion.
     */
    public void modificarDescripcion(int tipo) {

        switch (tipo) {
            case 1: {
                btnModificarDescripcion.setText("Guardar");
                txtAreaDescripcion.setEditable(true);
                txtAreaDescripcion.requestFocus(true);
                lblDescripcion.setText("Oprima ESC para cancelar");
            }
            break;
            case 2: {
                btnModificarDescripcion.setText("Editar descripción");
                txtAreaDescripcion.setEditable(false);
                lblDescripcion.setText("Descripción");
                txtAreaDescripcion.setText(descripcionEmpleado);
                panelPerfil.requestFocus();
            }
            break;

        }

        panelPerfil.updateUI();
    }

    public String getDescripcionEmpleado() {
        return descripcionEmpleado;
    }

    public void setDescripcionEmpleado(String descripcionEmpleado) {
        this.descripcionEmpleado = descripcionEmpleado;
    }
    
     public void asignarEscuchaBtnBuscar(ActionListener al) {

        btnBuscar.addActionListener(al);

    }

    public void asignarEscuchaBtnModificarDescripcion(ActionListener al) {
        btnModificarDescripcion.addActionListener(al);
    }
    
    public void asignarEscuchaBtnEnviarMensaje(ActionListener al){
        btnEnviarMensaje.addActionListener(al);
    }

    public void asignarEscuchaBtnEliminarPublicacion(ActionListener al) {
        btnEliminarPublicacion.addActionListener(al);
    }

    
    
    public void asignarEscuchaAreaDescripcion(KeyListener kl) {
        txtAreaDescripcion.addKeyListener(kl);
    }
    
    public JButton getBtnModificarDescripcion() {
        return btnModificarDescripcion;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public EscribirPublicacion getEscribirPublicacion() {
        return escribirPublicacion;
    }

    public JTextArea getTxtAreaDescripcion() {
        return txtAreaDescripcion;
    }

    public String getSexo() {
        return sexo;
    }

    public int getIdDependecia() {
        itemCombo item = (itemCombo) cbxDependecia.getSelectedItem();
        return item.getId();
    }

    public int getIdSubdependecia() {
        itemCombo item = (itemCombo) cbxSubdependecia.getSelectedItem();
        return item.getId();
    }

    public String getTxtNombreBusqueda() {
        return txtNombreBusqueda.getText().trim();
    }
     

    public String getTextAreaDescripcion() {
        return txtAreaDescripcion.getText().trim();
    }

    public JButton getBtnEnviarMensaje() {
        return btnEnviarMensaje;
    }  

    public JButton getBtnEliminarPublicacion() {
        return btnEliminarPublicacion;
    }

    public JButton getBtnEscribirPublicacion() {
        return btnEscribirPublicacion;
    }

    public void desplegarMensajeDialogo(int tipo, String titulo, String mensaje) {

        Toolkit.getDefaultToolkit().beep();

        switch (tipo) {

            case 1: {
                JOptionPane.showMessageDialog(null, mensaje, titulo,
                        JOptionPane.PLAIN_MESSAGE, obtenerIcono("/imagenes/error_icon.png"));
            }
            break;

            case 2: {
                JOptionPane.showMessageDialog(null, mensaje, titulo,
                        JOptionPane.PLAIN_MESSAGE, obtenerIcono("/imagenes/exito_icon.png"));
            }

        }
    }

    public int desplegarMensajeConfirmacion(String titulo, String mensaje) {
        Toolkit.getDefaultToolkit().beep();

        int respuesta = 0;
        respuesta = JOptionPane.showConfirmDialog(null, mensaje, titulo,
                JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                obtenerIcono("/imagenes/pregunta_icon.png"));

        return respuesta;

    }
    
 //DANIEL
    public void setImagenPerfil(ImageIcon imgIcon){  
        lblFoto.setIcon(imgIcon);
    }
    
    public void escuchaBtnCambiarFoto(ActionListener al){
        btnCambiarFoto.addActionListener(al);
    }
    
    public void escuchaBtnVerPerfil(ActionListener al){
        btnVerPerfil.addActionListener(al);
    }
    
    public JButton getBtnVerPerfil(){
        return btnVerPerfil; 
    }

    public JButton getBtnCambiarFoto(){
        return btnCambiarFoto;
    }
    
  //DANIEL

    /**
     * El propósito del método es obtener un icono relacionado con la URl para
     * desplegar JOptionPane personalizados
     *
     * @return El icono relacionado con la url
     */
    public Icon obtenerIcono(String url) {

        Icon icono;
        icono = new ImageIcon(new ImageIcon(getClass().getResource(""
                + url)).getImage());

        return icono;
    }
    
    public void cargarEmpleados(List<Empleado> empleados) {
        tableModel.setEmpleados(empleados);
        tablaBusqueda.updateUI();
    }
    
    public Empleado getEmpleadoFromTable() {

        Empleado empleado = tableModel.getEmpleadoAt(tablaBusqueda.getSelectedRow());
        
        return empleado;
    }
    
    private EscribirPublicacion escribirPublicacion;
    private ArrayList<JCheckBox> checkBoxesPublicaciones;
    private String descripcionEmpleado;
    private String sexo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Ventana;
    private javax.swing.JButton btnAbrirChat;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarMensaje;
    private javax.swing.JButton btnCambiarFoto;
    private javax.swing.JButton btnControlPublicaciones;
    private javax.swing.JButton btnEliminarPublicacion;
    private javax.swing.JButton btnEnviarMensaje;
    private javax.swing.JButton btnEscribirPublicacion;
    private javax.swing.JButton btnModificarDescripcion;
    private javax.swing.JButton btnVerPerfil;
    private javax.swing.JComboBox<itemCombo> cbxDependecia;
    private javax.swing.JComboBox<itemCombo> cbxSubdependecia;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreoValor;
    private javax.swing.JLabel lblDependencia;
    private javax.swing.JLabel lblDependenciaValor;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblInfomacionIcon;
    private javax.swing.JLabel lblInfomacionIcon1;
    private javax.swing.JLabel lblInformacion;
    private javax.swing.JLabel lblInformacion1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreValor;
    private javax.swing.JLabel lblSubdependencia;
    private javax.swing.JLabel lblSubdependenciaValor;
    private javax.swing.JPanel pane_lbl_Informacion;
    private javax.swing.JPanel pane_lbl_Publicaciones;
    private javax.swing.JPanel panelBandeja;
    private javax.swing.JPanel panelBuscador;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelContenedorPublicaciones;
    private javax.swing.JPanel panelControlPublicacion;
    private javax.swing.JPanel panelNotificaciones;
    private javax.swing.JPanel panelPerfil;
    private javax.swing.JPanel panelPublicaciones;
    private javax.swing.JPanel panel_Info_Perfil;
    private javax.swing.JScrollPane scrollPanePublicaciones;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTable tablaBusqueda;
    private javax.swing.JTextArea txtAreaDescripcion;
    private javax.swing.JTextArea txtAreaNotificaciones;
    private javax.swing.JTextField txtNombreBandeja;
    private javax.swing.JTextField txtNombreBusqueda;
    // End of variables declaration//GEN-END:variables

}
