/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JCheckBox;

/**
 *
 * @author dilan
 */
public class PublicacionPerfil extends javax.swing.JPanel {

    public PublicacionPerfil(String fecha, String hora, String contenido) {
        initComponents();
        
        lblFechaValor.setText(fecha);
        lblHoraValor.setText(hora);
        txtContenido.setText(contenido);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFechaPublicacion = new javax.swing.JLabel();
        lblHoraPublicacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContenido = new javax.swing.JTextArea();
        lblFechaValor = new javax.swing.JLabel();
        lblHoraValor = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 100));

        lblFechaPublicacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblFechaPublicacion.setText("Fecha: ");

        lblHoraPublicacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblHoraPublicacion.setText("Hora:");

        txtContenido.setEditable(false);
        txtContenido.setColumns(20);
        txtContenido.setRows(5);
        jScrollPane1.setViewportView(txtContenido);

        lblFechaValor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblFechaValor.setText("10 de Junio de 2021");

        lblHoraValor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblHoraValor.setText("12:37 pm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaPublicacion)
                            .addComponent(lblHoraPublicacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHoraValor)
                            .addComponent(lblFechaValor))
                        .addGap(8, 211, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaPublicacion)
                    .addComponent(lblFechaValor))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraPublicacion)
                    .addComponent(lblHoraValor))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFechaPublicacion;
    private javax.swing.JLabel lblFechaValor;
    private javax.swing.JLabel lblHoraPublicacion;
    private javax.swing.JLabel lblHoraValor;
    private javax.swing.JTextArea txtContenido;
    // End of variables declaration//GEN-END:variables
}
